[package]
name = "tui"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.98"
crossterm = "0.29.0"
futures = "0.3.31"
ratatui = { version = "0.29.0", features = ["crossterm"] }
tokio = { version = "1.44.2", features = ["full"] }
